name: "Tileboard Reborn Server"
version: "0.0.1"
slug: "tileboard_server"
description: "Server for the Tileboard Reborn dashboard"
url: "https://github.com/cgarwood/tileboard-server"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
ports:
  9090/tcp: 9090
ports_description:
  9090/tcp: "Tileboard Reborn Server - web UI and API"
map:
  - share:rw
options:
  port: 9090
schema:
  port: int
