haUrl: http://homeassistant.local
plex_token: 123456
snapcast_url: ws://192.168.1.2:1780
example_screensaver_source: https://example.com/get_pictures
example_screensaver_source_prefix: https://example.com